### ISSUE TITLE
Todos of Cool ToDo List

### ISSUE THREAD

**Issue by szuhaydv** [Szuhaydv/Cool-ToDo-List#1]
- [ ] **Log-in View**
   - [ ] Showing logo and welcome message 
   - [ ] Log-in with e-mail/password
   - [ ] Log-in with Google
   - [ ] Log-in with Apple
- [ ] **Calendar View**
   - [x] Calendar showing the days of this month
      - [ ] Selection functionality
      - [ ] Color Functionality (based on number of tasks for the day)
   - [ ] Filter options
      - [x] 'Menu' opening on tap
         - [ ] Fix: Tap area should be the whole button, not just the label 
      - [ ] Functionality & Logic
   - [x] ScrollView of selected day's tasks
   - [ ] Scale Sidebar showing the hours
      - [x] Scale
      - [ ] Hours 
   - [ ] Showing tasks at the correct position, based on starting time and length
- [ ] **Tasks View**
   - [x] UI Layout
   - [ ] Functionality 
      - [ ] Current Days Slider
      - [x] Unsorted Tasks area
         - [ ] Maybe: Chevron button left/right 
         - [x] Info Popover
      - [ ] Top Three Tasks area
         - [ ] Info Popover
         - [x] Progress loading in circle
         - [ ] Quote (maybe from API)
         - [ ] Top Three Tasks showing up (based on priority logic) 
            - [ ] Swap function - If you want to focus on a different task
            - [ ] Complete Task Function
   - [ ] Populated by data 
- [ ] **Statistics View**
   - [x] UI Layout
   - [ ] Populate with data
      - [ ] Display Tasks Info (number of tasks last week / completed / failed)
      - [ ] Chart showing the distribution of tasks for each day
   - [ ] 'Add note for this week' function
- [ ] **TabBar**
   - [ ] Rounded middle button
   - [ ] Entering Tasks View middle button turns into 'Add' icon
- [ ] **Add Task View**
